scrape_configs:
  - job_name: test_json
    static_configs:
    - targets:
        - localhost
      labels:
            type:     test
            __path__: /tmp/test-*.json
    pipeline_stages:
      - regex:
          expression: "^(?P<timestamp>(\\d+-\\d+-\\d+ \\d+:\\d+:\\d+)) (?P<message>.*)"
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
          location: "Europe/Rome"
      - output:
          source: message
